name: Lint

on: 
  - push
  - pull_request
  - workflow_dispatch

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test files formatting
        uses: psf/black@stable
      - name: remove nb outputs
        uses: 